server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store-password: ${server_ssl_key_store_password}
    protocol: TLS
    enabled-protocols: TLSv1.2
    key-store: ${server_ssl_key_store}
    ciphers: ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHERSA-AES128-SHA:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384
  port: 8080
  servlet:
    session:
      timeout: 3600
      cookie:
        name: JSESSIONID
        domain: musicdiary.life
        http-only: true
        path: /


spotify:
  clientId: ${spotify_clientId}
  clientSecret: ${spotify_clientSecret}

oauth:
  kakao:
    grantType: authorization_code
    clientId: ${oauth_kakao_clientId}
    redirectUri: ${oauth_kakao_redirectUri}
    tokenUri: https://kauth.kakao.com/oauth/token
    userInfoUri: https://kapi.kakao.com/v2/user/me
    logoutRedirectUri: ${oauth_kakao_logoutRedirectUri}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring_datasource_url}
    username: ${spring_datasource_username}
    password: ${spring_datasource_password}
    initialization-mode: always

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

    sql:
      init:
        mode: always

    logging:
      level:
        org.hibernate.sql: debug
        org.hibernate.type.descriptor.sql: trace