server:
  port: 8080
  servlet:
    session:
      timeout: 3600
      cookie:
        name: JSESSIONID
        domain: 3.38.153.192
        http-only: true
        path: /


spotify:
  clientId: ${spotify_clientId}
  clientSecret: ${spotify_clientSecret}

oauth:
  kakao:
    grantType: authorization_code
    clientId: ${oauth_kakao_clientId}
    redirectUri: http://3.38.153.192/oauth/kakao
    tokenUri: https://kauth.kakao.com/oauth/token
    userInfoUri: https://kapi.kakao.com/v2/user/me
    logoutRedirectUri: http://3.38.153.192/logout

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring_datasource_url}
    username: ${spring_datasource_username}
    password: ${spring_datasource_password}
    initialization-mode: always

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

    sql:
      init:
        mode: always

    logging:
      level:
        org.hibernate.sql: debug
        org.hibernate.type.descriptor.sql: trace